CFG_ANDROID_SDK_BUILD_TOOL = 26.0.2
CFG_ANDROID_SDK_PLATFORM = android-26

CFG_APK_NAME = template
CFG_PACKAGE_NAME = com.brickredstudio.template

CFG_RESOURCES = \
res/drawable-xhdpi/app_icon.png \
res/layout/activity_main.xml \
res/values/strings.xml \

CFG_SOURCES = \
src/com/brickredstudio/template/MainActivity.java \

include mak/main.mak
